apiVersion: v1
kind: Service
metadata:
  name: {{ .openapp.instance_name }}
  namespace: openapp
spec:
  ports:
    - port: 7400
      targetPort: 7400
  type: NodePort
  selector:
    publicservice: {{ .openapp.instance_name }}
