name: OpenAPP templates image build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set Up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build images
      run: |
        bash hack/image-build.sh

    - name: Push to Docker Hub
      run: |
        all_images=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep opennaslab)
        for image in $all_images; do
          docker push $image
        done
